name:                real-world-haskell-updated
version:             0.1.0.0
github:              "githubuser/real-world-haskell-updated"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/real-world-haskell-updated#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  real-world-haskell-updated-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated

  wc:
    main:                wc.hs
    source-dirs:         app/ch01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated  

  interact:
    main:                interactWith.hs
    source-dirs:         app/ch04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated  

  fixLines:
    main:                fixLines.hs
    source-dirs:         app/ch04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated  

  simple:
    main:                Main.hs
    source-dirs:         app/ch05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated 

tests:
  real-world-haskell-updated-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-updated
